In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism-preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets

In [7]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [8]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis = 1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive Absenteeism  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

In [10]:
data_with_targets.shape

(700, 15)

In [11]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
absenteeism_scaler = StandardScaler()

In [14]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\Lindsay\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [15]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

C:\Users\Lindsay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


In [16]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [17]:
scaled_inputs.shape

(700, 14)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

C:\Users\Lindsay\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [20]:
print(x_train.shape, y_train.shape)

(560, 14) (560,)


In [21]:
print(x_test.shape, y_test.shape)

(140, 14) (140,)


In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [23]:
reg = LogisticRegression()

In [24]:
reg.fit(x_train, y_train)

C:\Users\Lindsay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [25]:
reg.score(x_train, y_train)

0.7803571428571429

In [26]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [27]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [28]:
model_outputs == y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [29]:
h = np.sum((model_outputs == y_train))

In [30]:
i = model_outputs.shape[0]

In [31]:
h/i

0.7803571428571429

### Interpreting the model

In [32]:
reg.intercept_

array([-0.20908973])

In [33]:
reg.coef_

array([[ 2.07044024,  0.33037751,  1.56321412,  1.31103462,  0.02578678,
        -0.08632909,  0.7233164 , -0.06154754, -0.20633005, -0.02869987,
         0.32595295, -0.1615189 ,  0.38151211, -0.32141202]])

In [34]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [35]:
feature_name = unscaled_inputs.columns.values

In [36]:
summary_table = pd.DataFrame (columns = ['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                  Reason_1     2.070440
1                  Reason_2     0.330378
2                  Reason_3     1.563214
3                  Reason_4     1.311035
4               Month Value     0.025787
5           Day of the Week    -0.086329
6    Transportation Expense     0.723316
7          Distance to Work    -0.061548
8                       Age    -0.206330
9   Daily Work Load Average    -0.028700
10          Body Mass Index     0.325953
11                Education    -0.161519
12                 Children     0.381512
13                      Pet    -0.321412

In [37]:
summary_table.index = summary_table.index + 1
summary_table

Feature name  Coefficient
1                  Reason_1     2.070440
2                  Reason_2     0.330378
3                  Reason_3     1.563214
4                  Reason_4     1.311035
5               Month Value     0.025787
6           Day of the Week    -0.086329
7    Transportation Expense     0.723316
8          Distance to Work    -0.061548
9                       Age    -0.206330
10  Daily Work Load Average    -0.028700
11          Body Mass Index     0.325953
12                Education    -0.161519
13                 Children     0.381512
14                      Pet    -0.321412

In [38]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.209090
1                  Reason_1     2.070440
2                  Reason_2     0.330378
3                  Reason_3     1.563214
4                  Reason_4     1.311035
5               Month Value     0.025787
6           Day of the Week    -0.086329
7    Transportation Expense     0.723316
8          Distance to Work    -0.061548
9                       Age    -0.206330
10  Daily Work Load Average    -0.028700
11          Body Mass Index     0.325953
12                Education    -0.161519
13                 Children     0.381512
14                      Pet    -0.321412

In [39]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.209090    0.811322
1                  Reason_1     2.070440    7.928313
2                  Reason_2     0.330378    1.391493
3                  Reason_3     1.563214    4.774141
4                  Reason_4     1.311035    3.710010
5               Month Value     0.025787    1.026122
6           Day of the Week    -0.086329    0.917292
7    Transportation Expense     0.723316    2.061258
8          Distance to Work    -0.061548    0.940308
9                       Age    -0.206330    0.813565
10  Daily Work Load Average    -0.028700    0.971708
11          Body Mass Index     0.325953    1.385350
12                Education    -0.161519    0.850850
13                 Children     0.381512    1.464497
14                      Pet    -0.321412    0.725124

In [40]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                  Reason_1     2.070440    7.928313
3                  Reason_3     1.563214    4.774141
4                  Reason_4     1.311035    3.710010
7    Transportation Expense     0.723316    2.061258
13                 Children     0.381512    1.464497
2                  Reason_2     0.330378    1.391493
11          Body Mass Index     0.325953    1.385350
5               Month Value     0.025787    1.026122
10  Daily Work Load Average    -0.028700    0.971708
8          Distance to Work    -0.061548    0.940308
6           Day of the Week    -0.086329    0.917292
12                Education    -0.161519    0.850850
9                       Age    -0.206330    0.813565
0                 Intercept    -0.209090    0.811322
14                      Pet    -0.321412    0.725124

### Testing the model

In [42]:
reg.score(x_test,y_test)

0.7285714285714285

In [43]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.76452451, 0.23547549],
       [0.61145728, 0.38854272],
       [0.40725279, 0.59274721],
       [0.78525018, 0.21474982],
       [0.06069289, 0.93930711],
       [0.26735152, 0.73264848],
       [0.28560686, 0.71439314],
       [0.06669019, 0.93330981],
       [0.75821056, 0.24178944],
       [0.76495206, 0.23504794],
       [0.47304059, 0.52695941],
       [0.13528622, 0.86471378],
       [0.0415479 , 0.9584521 ],
       [0.69530741, 0.30469259],
       [0.20565571, 0.79434429],
       [0.47658141, 0.52341859],
       [0.49282929, 0.50717071],
       [0.53845181, 0.46154819],
       [0.37773399, 0.62226601],
       [0.02911245, 0.97088755],
       [0.73347379, 0.26652621],
       [0.77686497, 0.22313503],
       [0.42513764, 0.57486236],
       [0.44163669, 0.55836331],
       [0.15225758, 0.84774242],
       [0.75970453, 0.24029547],
       [0.45561429, 0.54438571],
       [0.89827183, 0.10172817],
       [0.16280027, 0.83719973],
       [0.76824898, 0.23175102],
       [0.

In [44]:
predicted_proba[:, 1]

array([0.23547549, 0.38854272, 0.59274721, 0.21474982, 0.93930711,
       0.73264848, 0.71439314, 0.93330981, 0.24178944, 0.23504794,
       0.52695941, 0.86471378, 0.9584521 , 0.30469259, 0.79434429,
       0.52341859, 0.50717071, 0.46154819, 0.62226601, 0.97088755,
       0.26652621, 0.22313503, 0.57486236, 0.55836331, 0.84774242,
       0.24029547, 0.54438571, 0.10172817, 0.83719973, 0.23175102,
       0.41443589, 0.74210565, 0.70090819, 0.529598  , 0.22313503,
       0.61638864, 0.25839797, 0.83263799, 0.47517829, 0.60699198,
       0.24263801, 0.4172944 , 0.23525506, 0.09841694, 0.82768361,
       0.73321624, 0.76247917, 0.24134544, 0.27245325, 0.20140846,
       0.49918528, 0.07041061, 0.70520113, 0.26244884, 0.86864561,
       0.44163379, 0.95247652, 0.29276888, 0.07816544, 0.07671065,
       0.74471783, 0.68046073, 0.28780636, 0.859132  , 0.23921894,
       0.23758575, 0.01170298, 0.24542914, 0.84469409, 0.3120185 ,
       0.24450323, 0.07853439, 0.92247827, 0.46733493, 0.65211

### Save the model

In [45]:
import pickle

In [46]:
with open('absenteeism_model', 'wb') as file:
    pickle.dump(reg, file)

In [47]:
with open('absenteeism_scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)